# 发布 my-dep 服务
apiVersion: v1
kind: Service
metadata:
  name: my-dep
  labels: # 和my-dep.yaml 的元数据的 labels 一致（有一个一样即可）
    app: nginx
    env: dep
spec:
  selector: # 和my-dep.yaml template 的元数据的 labels 一致（有一个一样即可）
    app: nginx
    env: dep
  ports: # 暴露端口
    - name: nginx-ports
      protocol: TCP
      port: 80 # pod的80端口，service和pod通讯使用的端口
      nodePort: 30001 # 暴露到物理机端口 范围30000-32767
      targetPort: 80 # 收到请求发送到pod的80 端口
  type: NodePort